---
application:
  name: "wp-app"
  project: "Wordpress-deleted-1618680404737"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "wp-db"
  version: "5.7"
routers:
- name: "main-wp-app"
  routes:
  - application_name: "wp-app"
    paths:
    - "/*"
