---
application:
  name: "wp"
  project: "cidades"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "wp"
  version: "5.7"
routers:
- name: "main-wp"
  routes:
  - application_name: "wp"
    paths:
    - "/*"
