---
application:
  name: "wordpress"
  project: "Wordpress"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "wordpress"
  version: "8.0"
routers:
- name: "main-wordpress"
  routes:
  - application_name: "wordpress"
    paths:
    - "/*"
